---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  browser: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - "plugin:react/recommended"

rules:
  max-len: ["error", { "code": 120, "ignoreUrls": true }]
  object-property-newline: off
  react/prop-types: 0